### ISSUE TITLE
[Feature] Parsing placeholders within a RP placeholder

### ISSUE THREAD

**Issue by ASlipperySlope** [Lorenzo0111/RocketPlaceholders#116]
**What type of feature is it?**
The feature to parse a placeholder inside of a RocketPlaceholders placeholder.
`%rp_custom_placeholder_%other_placeholder%%` or anything of this nature.

Example: 
If `%other_placeholder%` value is **test**, it will parse as `%rp_custom_placeholder_test%`

**Comment by Lorenzo0111** [comment]
I don't think it's doable, i'll try

**Comment by ASlipperySlope** [comment]
I switched away from this placeholder plugin a long time ago. It's no longer necessary for me personally.
