### ISSUE TITLE
[Feature] Color Codes

### ISSUE THREAD

**Issue by mitchngwen** [Lorenzo0111/RocketPlaceholders#121]
**What type of feature is it?**
Color Code support for placeholders.

**Describe your feature**
Here is an example:
    placeholder: "class"
    text: "&6You don't have a class"
    conditions:
      swords:
        type: PERMISSION
        value: "mcmmo.perks.xp.customboost.swords"
        text: "&#FDFD96ᴡᴀʀʀɪᴏʀ&e"

**Comment by Lorenzo0111** [comment]
This is already implemented.
